name = "automotive-autoregal-glmai17"
main = "worker.js"
compatibility_date = "2026-07-29"

[assets]
directory = "./public"
run_worker_first = true
not_found_handling = "single-page-application"

[ai]
binding = "AI"
